name: Semgrep

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM within 06:00-09:00 UTC to spread runner load
    - cron: '21 08 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Setup
        uses: SierranaTech/actions/setup@main
      - name: Semgrep scan
        uses: SierranaTech/actions/semgrep@main
